print ("Python")
print ("\tPython")
print (" ")
print ("Languages: \nPython\nC\nJava-script")
print (" ")
print ("Languages: \n\tPython\n\tC\n\tJava-script")
print (" ")
print ("Stripping Whitespace")
print (" ")
favorite_language = 'python '
print (favorite_language)
print (favorite_language.rstrip())
print (favorite_language)

favorite_language = favorite_language.rstrip()
print (favorite_language)
